---
- hosts: sandboxapicdc.cisco.com
  gather_facts: no
  vars_files: 
  - ./vars/aci.yml
  tasks:
    - name: Remove an ACI tenant
      cisco.aci.aci_tenant:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: production-xyz
        description: Production xyz tenant
        state: absent
      delegate_to: localhost
