---
- name: Adding ACI fabric access policies for interfaces using a CSV file
  hosts: sandboxapicdc.cisco.com
  gather_facts: no
  vars_files: 
  - ./vars/creds.yml
  tasks:

    - name: Gather facts from CSV file
      read_csv:
        path: aci-config/fabric-ap-int-policy.csv
      #register in the config list:
      register: config
      delegate_to: localhost

    - name: Create a Virtual Port Channel (VPC) or Port Channel Interface Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        lag_type: "{{ index.linktype }}"
        policy_group: "{{ index.intpolicy }}"
        aep: "{{ index.aep }}"
        link_level_policy: "{{ index.speedpolicy }}"
        cdp_policy: "{{ index.cdppolicy }}"
        lldp_policy: "{{ index.lldppolicy }}"
        port_channel_policy: "{{ index.pcpolicy }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      when: ("{{ index.linktype }}" != "leaf")
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - name: Create a Leaf Access Port Policy Group
      cisco.aci.aci_interface_policy_leaf_policy_group:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        lag_type: "{{ index.linktype }}"
        policy_group: "{{ index.intpolicy }}"
        aep: "{{ index.aep }}"
        link_level_policy: "{{ index.speedpolicy }}"
        cdp_policy: "{{ index.cdppolicy }}"
        lldp_policy: "{{ index.lldppolicy }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      when: ("{{ index.linktype }}" == "leaf")
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - debug:
        msg: "{{ index.intpolicy }} - {{ index.linktype }} - {{ index.state }}"
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - name: Gather facts from CSV file
      read_csv:
        path: aci-config/fabric-ap-int-block.csv
      #register in the config list:
      register: config
      delegate_to: localhost

    - name: Associate an Interface Access Port Selector to an Interface Policy Leaf Profile with a Policy Group
      cisco.aci.aci_access_port_to_interface_policy_leaf_profile:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        interface_profile: "{{ index.intleafprf }}"
        access_port_selector: "{{ index.intname }}"
        port_blk: "{{ index.intname }}"
        from_port: "{{ index.intfrom }}"
        to_port: "{{ index.intto }}"
        policy_group: "{{ index.intpolicy }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - debug:
        msg: "{{ index.intleafprf }} - {{ index.intname }} - {{ index.intfrom }} - {{ index.intto }} - {{ index.intpolicy }} - {{ index.state }}"
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index
