---
- hosts: sandboxapicdc.cisco.com
  gather_facts: no
  vars_files: 
  - ./vars/aci.yml
  tasks:
    - name: Query all ACI bridge domain
      cisco.aci.aci_bd:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        state: query
      delegate_to: localhost
      register: query_result
      
    - debug:
        var: query_result
