---
- name: "Configuring ACI Tenant, VRF, AP, BD and EPG's using a CSV file"
  hosts: sandboxapicdc.cisco.com
  gather_facts: no
  vars_files: 
  - ./vars/aci.yml
  tasks:

    - name: "Gather facts from Tenant & VRF CSV file"
      read_csv:
        path: aci-config/tn-config.csv
      #register in the config list:
      register: config
      delegate_to: localhost

    - name: "Configure Tenants - do not use CSV to remove Tenants"
      cisco.aci.aci_tenant:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ index.tenant }}"
        description: "{{ index.tndescription }}"
        state: present
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - name: "Configure VRFs within Tenants"
      cisco.aci.aci_vrf:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        vrf: "{{ index.vrf }}"
        tenant: "{{ index.tenant }}"
        descr: "{{ index.vrfdescription }}"
        policy_control_preference: "{{ index.vrfpref }}"
        policy_control_direction: "{{ index.vrfdirection }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - debug:
        msg: "{{ index.tenant }} - {{ index.vrf }}"
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index
    
    - name: "Gather facts from Bridge Domain CSV file"
      read_csv:
        path: aci-config/bd-config.csv
      #register in the config list:
      register: config
      delegate_to: localhost

    - name: "Configure Bridge Domains within Tenants"
      cisco.aci.aci_bd:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ index.tenant }}"
        vrf: "{{ index.vrf }}"
        bd: "{{ index.bd }}"
        enable_routing: "{{ index.enable_routing }}"
        arp_flooding: "{{ index.arp_flooding }}"
        limit_ip_learn: "{{ index.limit_ip_learn }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - name: "Configure Subnets within Bridge Domains"
      cisco.aci.aci_bd_subnet:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ index.tenant }}"
        bd: "{{ index.bd }}"
        gateway: "{{ index.gateway }}"
        mask: "{{ index.mask }}"
        scope: "{{ index.scope }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index
 
    - name: "Configrue L3Outs within Bridge Domains"
      cisco.aci.aci_bd_to_l3out:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ index.tenant }}"
        bd: "{{ index.bd }}"
        l3out: "{{ index.l3out }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index
    
    - debug:
        msg: "{{ index.tenant }} - {{ index.vrf }} - {{ index.bd }} - {{ index.gateway }} - {{ index.mask }} - {{ index.scope }}"
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - name: "Gather facts from AP & EPG CSV file"
      read_csv:
        path: aci-config/epg-config.csv
      #register in the config list:
      register: config
      delegate_to: localhost
    - name: "Configure Application Profiles - do not use to remove AP"
      cisco.aci.aci_ap:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ index.tenant }}"
        ap: "{{ index.ap }}"
        description: "{{ index.apdescription }}"
        monitoring_policy: default
        state: present
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - name: "Configure EPGs within Tenants"
      cisco.aci.aci_epg:
        host: "{{ apic }}"
        username: "{{ aci_username }}"
        password: "{{ aci_password }}"
        validate_certs: no
        tenant: "{{ index.tenant }}"
        ap: "{{ index.ap }}"
        epg: "{{ index.epg }}"
        description: "{{ index.epgdescription }}"
        bd: "{{ index.bd }}"
        monitoring_policy: default
        preferred_group: "{{ index.prefgroup }}"
        state: "{{ index.state }}"
      delegate_to: localhost
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index

    - debug:
        msg: "{{ index.tenant }} - {{ index.ap }} - {{ index.bd }} - {{ index.epg }}"
      loop: "{{ config.list }}"
      loop_control:
        loop_var: index


